### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by easyfrog** [sublimelsp/LSP-svelte#64]
env:

* sublime text 4
* LSP v1.12.1
* LSP-typescript v1.6.0
* LSP-svelte v1.1.20
* node v16.8.0
* python v3.7.4
* Mac 11.6

when type codes in svelte component's `<script>` tag, I got error below.

```
Error handling None
Traceback (most recent call last):
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 1616, in on_payload
    handler(result)
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 153, in <lambda>
    executor_func(lambda value=None: self._do_resolve(value))
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 214, in _do_resolve
    callback(new_value)
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 184, in callback_wrapper
    resolve_fn(result)
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 153, in <lambda>
    executor_func(lambda value=None: self._do_resolve(value))
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 214, in _do_resolve
    callback(new_value)
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 178, in callback_wrapper
    result = onfullfilled(resolve_value)
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 132, in recheck_resolve_status
    resolve(values)
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 153, in <lambda>
    executor_func(lambda value=None: self._do_resolve(value))
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 214, in _do_resolve
    callback(new_value)
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/promise.py", line 178, in callback_wrapper
    result = onfullfilled(resolve_value)
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/documents.py", line 658, in <lambda>
    lambda responses: self._on_all_settled(responses, resolve_completion_list))
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/documents.py", line 688, in _on_all_settled
    response_items = sorted(response_items, key=lambda item: item.get("sortText") or item["label"])
  File "/Users/easyfrog/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/documents.py", line 688, in <lambda>
    response_items = sorted(response_items, key=lambda item: item.get("sortText") or item["label"])
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by easyfrog** [comment]
Solve it: must has a `jsconfig.json` or `tsconfig.jsfon` in the project's folder
